# Your Name or Company
title: jason cho 

# Description of your website. This is used for social sharing.
description:  the site of engineer, cyclist, musiction, and travller, Jason Cho.

# A brief blurb about yourself
content: a highly technical and experienced professional, capable of understanding the complexities of large IT environments and enterprise applications. 

# Add your social links
social:
#  - platform: github
#    url: https://github.com/chunchae
  - platform: instagram
    url: https://www.instagram.com/__jason.kr__/
  - platform: strava
    url: https://www.strava.com/athletes/jasonkr

# General settings
# url: http://jason.kr
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "G-ZG3JH5H3VT" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
